//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.TravelOffer = new HashSet<TravelOffer>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        private ICollection<TravelOffer> TravelOffer { get; set; }
    }
}
