//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelOffer
    {
        public TravelOffer()
        {
            this.Country = new HashSet<Country>();
        }
    
        public int OfferId { get; set; }
        public Nullable<double> PricePerPerson { get; set; }
    
        public virtual ICollection<Country> Country { get; set; }
    }
}
